version: 1.0.{build}

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

branches:
    only:
      - master

cache:
    - packages -> **\packages.config
    - C:\downloads -> appveyor.yml

configuration: Release
